### ISSUE TITLE
Use better namespacing of helpers?

### ISSUE THREAD

**Issue by raix** [raix/Meteor-handlebar-helpers#14]
Should not be prefixed with `$.`:
* `Session`
* `Meteor`
*These will prop. be added like this in the new UI anyway*

I predict that symbols/exports from packages will be added to the helper scope in the new UI,

This will lead to incompatibility between handlebar-helpers and jQuery, that will be kind of a problem...

Maybe use `Helper` instead of `$`?

Should be prefixed by `Helper.`:
* getLength
* cutString
* isSelected
* isChecked
* getText

Not sure if all the operators like `$exists`, `$gt` should be prefixed by `Helper.`?
I really hope that these will deprecate in favor of a js like syntax in the templates:
```html
  {{#if (a > b) || (c > d)}}
  ...
  {{/if}}
```

It would simplify the code and maybe make it a bit easier to work with?

**Comment by serkandurusoy** [comment]
@raix I don't think you'll get over such dilemma even with the new Meter 1.2 enhancements, although nested helpers kind of make it easier to craft expressions. But inline javascript expressions were discussed and not accepted into core spacebars.

So, after almost 2 years of how handlebars-helpers is what it is, I guess you want to mark this closed? 

:))

In fact, I'm gonna go ahead and make that tough decision for you ;)

**Comment by raix** [comment]
thanks :)
