### ISSUE TITLE
Add a helper for global variables

### ISSUE THREAD

**Issue by Neobii** [raix/Meteor-handlebar-helpers#16]
Example:

```javascript
GlobalObjects = [{
  label: "testObject1"
},
  label: "testObject2"
}];
```

```html
{{#each $.GlobalObjects}}
  <p>{{label}}</p>
{{/each}}
```

**Comment by serkandurusoy** [comment]
@raix I don't quite get the argument here, perhaps this is an old thread and I don't know the situation at that point in time, but to me, it seems today we can achieve this functionality with the help of `addScope`.

So should we go ahead and mark this as closed?

**Comment by serkandurusoy** [comment]
This works. Take a look at http://meteorpad.com/pad/wfqo2GG2MYSQcdw4Y/Helpers.addScope()%20example

But please do reopen if I'm missing the obvious here :)
