### ISSUE TITLE
nl2br helper

### ISSUE THREAD

**Issue by dohomi** [raix/Meteor-handlebar-helpers#26]
What would you think to add a nl2br helper? This is the code I currently use:
```
UI.registerHelper('nl2br', function(text) {
    var nl2br = (text + '').replace(/([^>\r\n]?)(\r\n|\n\r|\r|\n)/g, '$1' + '<br>' + '$2');
    return new Spacebars.SafeString(nl2br);
});
```
Nice collection of helpers by the way!

**Comment by chuikoffru** [comment]
thank you! very nice!

**Comment by serkandurusoy** [comment]
This looks as if it works as expected. @alexzaporozhets please let us know if you are still experiencing problems with the `nl2br` helper.
