### ISSUE TITLE
{{$.Session.notequals key value}} - Helper

### ISSUE THREAD

**Issue by wbashir** [raix/Meteor-handlebar-helpers#27]
Is there a `not equals` helper or could I build this somehow with what is provided ?

**Comment by newswim** [comment]
Could {{#unless}} perform the task? It's basically the inverse of {{#if}}

**Comment by wbashir** [comment]
I was actually looking for an `a` `b` comparison helper and didn't see this one `{{$neq a b}} if not a equals b then return true`
