### ISSUE TITLE
Use true / false in session set 

### ISSUE THREAD

**Issue by almogdesign** [raix/Meteor-handlebar-helpers#29]
It would be nice if session set could support a boolean value. 

Like 
Session.set('hasLinks', true); or Session.set('hasLinks', false); 

Right now you have to use strings

**Comment by serkandurusoy** [comment]
Marking closed as left inactive for months now. If you are still having a problem with how Session works and how it pertains to handlebars-helpers, please reopen for further discussion. Thanks.
