### ISSUE TITLE
Feature request: Pluralisation

### ISSUE THREAD

**Issue by yogiben** [raix/Meteor-handlebar-helpers#31]
{{$pl 'post', 'posts', value}}

where the first is selected only if the value is 1

**Comment by MattiSG** [comment]
Why not keep these helpers focused on helpers and leaving i18n to [`tap:i18n`](https://atmospherejs.com/tap/i18n)?  :)

**Comment by serkandurusoy** [comment]
I agree with i18n being out of scope for a general helpers package. And if we did do this, I'd be disappointed to support ony English. My native tounge is Turkish and you won't believe the intricacies involved with pluralization and I know it is not the hardest of languages out there!

So, @raix what do you think? Should we bow out and close this?

**Comment by raix** [comment]
agree - I think mozilla presented a really nice pattern for this adopted by react as I recall - but be should prop. adapt that in a separate package. I think it was http://formatjs.io/

**Comment by serkandurusoy** [comment]
I think [gadicohen:messageformat](https://atmospherejs.com/gadicohen/messageformat) also addresses this with the same semantics.
