### ISSUE TITLE
$.Session.get 'doc' property

### ISSUE THREAD

**Issue by yogiben** [raix/Meteor-handlebar-helpers#33]
I often store the current doc in the Session variable 'doc' etc.

In my templates, I generally need to render a property of the doc.

I could solve this by
```
UI.registesterHelper 'doc', ->
  Session.get 'doc'
```
and then
```
{{doc.title}}
```
but it would be even better if I could use a helper to render the property directly
```
$.Session.get 'doc' 'title'
```
Is there an existing way to do this? I feel like hanldebars is limited by its incompatibility with nesting formulas given the use of spaces instead of brackets and commas.

**Comment by serkandurusoy** [comment]
The new `let` syntax, ``with` an nested helpers that come with Meteor 1.2 provide multiple ways to solve this problem. Please reopen if you disagree. Thanks for bringing this up anyway.
