### ISSUE TITLE
enhancement for cutString

### ISSUE THREAD

**Issue by dohomi** [raix/Meteor-handlebar-helpers#39]
Hey, just realises that the cutString has an edge case if the str is HTML and not plain text. Maybe clean HTML first?
```
UI.registerHelper('cutString', function (str, len) {
      str = $(str).text();
      return (str.length > len)?str.substr(0, Math.max(len-3, 0))+'...':str;
    });
```
What do you think?

**Comment by serkandurusoy** [comment]
@dohomi this is an intricate issue to deal with. You can create dedicated helpers 

plain text: the built-in one here or http://epeli.github.io/underscore.string/#prune-string-length-prunestring-gt-string for something more advanced

html: http://codereview.stackexchange.com/questions/92801/truncating-text-with-jquery-but-keep-the-html-formatting or http://tcorral.github.io/Cutter.js/ or https://github.com/huang47/nodejs-html-truncate

markdown: I could not actually find anything that does markdown truncation, but perhaps one could take cue from the html truncators mentioned above to create one.

I frankly don't think such very dedicated helpers have place in a general helper package, but please make your case if you disagree with me. I'd be happy to discuss its pros and cons.

PS: My search also yielded https://github.com/uplift/bullhorn-handlebars-helpers from which you/we could perhaps take inspiration.

Thank you.

**Comment by dohomi** [comment]
@serkandurusoy all good for me, I went with another solution and away from Blaze. Thanks getting back to me, cheers!
