### ISSUE TITLE
css is not loading 

### ISSUE THREAD

**Issue by Hareramrai** [raix/Meteor-handlebar-helpers#49]
Hi, 

I am using this package for sending an email from server side. But it's failed to load css class for html element. 

Can some help me to load css class in email. 

Thanks,
Hare

**Comment by raix** [comment]
Most email readers only support inline styles.
Not if this package works on the server?

**Comment by raix** [comment]
In file styles... Style tags inline

**Comment by serkandurusoy** [comment]
Marking closed as left inactive for months now.
