### ISSUE TITLE
Helpers.addScope() unresponsive

### ISSUE THREAD

**Issue by KristerV** [raix/Meteor-handlebar-helpers#52]
No errors no nothing, just does not work.

**HTML**

	<body>
	  <h1>Welcome to Meteor!</h1>
		<p>{{$.simpleString}}</p>

	  	{{#if $.Client.isSatisfied}}
	  		<p>Client is satisfied</p>
		{{/if}}
	</body>

**JavaScript**

    Meteor.startup(function(){
      if (Meteor.isClient) {
        console.log("Do I get fired?")
    
        Client = {}
        Client.isSatisfied = function() { return true}
        Helpers.addScope('Client', Client);

        simpleString = "hey"
        Helpers.addScope('simpleString', simpleString);
      }
    })

The code `console.log("Do I get fired?")` gets printed into the console just fine.

**Comment by serkandurusoy** [comment]
@KristerV  this works if you take the code out of the startup block which in fact defers the execution of its contents until after everything else has loaded, hence not making the scoped helpers available to spacebars.

Take a look at http://meteorpad.com/pad/wfqo2GG2MYSQcdw4Y/Helpers.addScope()%20example for working demo.
