### ISSUE TITLE
isCkecked throws Error: Expected valid attribute name, '', null, or object

### ISSUE THREAD

**Issue by darkship** [raix/Meteor-handlebar-helpers#53]
Hi,
Calling <code>isChecked</code> in an input throws <code>Error: Expected valid attribute name, '', null, or object</code>. https://github.com/darkship/test_template_helpers_isChecked

When you remove the white space it should work : 
```
UI.registerHelper('isSelected', function (a, b) {
      return (a === b)?'selected': '';
    });
```

**Comment by chafey** [comment]
I ran into this same issue and think it also applies to isSelected.  I can submit a PR if needed, but the change is trivial (remove the leading space).  Would also be nice to include a test and example of these features in case people aren't sure how to use them (like i was... then debugged and found it was a bug....)

**Comment by shaneseaton** [comment]
+1

**Comment by serkandurusoy** [comment]
This will have been fixed with the next release that includes the aforementioned PR. Thanks for reporting this.
