### ISSUE TITLE
Multiple condition in one handle bar

### ISSUE THREAD

**Issue by leizard** [raix/Meteor-handlebar-helpers#61]
Hi, thank you for awesome package, I use it alot. Could I use something like this ?

```
 {{#if $and $eq folders.length 0 $eq files.length 0}}
```
folders and files are my 2 helpers, which return folder array and file array.
It seem not work in my app.
Thank you

**Comment by raix** [comment]
I think spacebars now support the use of `()` eg.:
```js
{{#if $and ($eq folders.length 0) ($eq files.length 0) }}
```

**Comment by leizard** [comment]
it works. thank you!
