### ISSUE TITLE
How many parameters could $in take?

### ISSUE THREAD

**Issue by daveeel** [raix/Meteor-handlebar-helpers#63]
It seems that the $in operator has very limited number of parameter?

It stops to work when I have say five parameters like the following (I use .jade):

```jade
if $in gameState 'S1' 'S2' 'S3' 'S4' 'S5'
  div ...
```

With less parameters, say 3 works fine.

**Comment by serkandurusoy** [comment]
It takes 4. There is a pull request #60 related to this. You can show your support there if you really want this.
